//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_elektryk
{
    using System;
    using System.Collections.Generic;
    
    public partial class adres
    {
        public int ID { get; set; }
        public string Miasto { get; set; }
        public string Kod_pocztowy { get; set; }
        public string Nazwa_ulicy { get; set; }
        public string Numer_budynku { get; set; }
        public string Numer_mieszkania { get; set; }
        public string Państwo { get; set; }
    }
}
