//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_elektryk
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dane_Logowania
    {
        public string Login { get; set; }
        public string Hasło { get; set; }
    }
}
