//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_elektryk
{
    using System;
    using System.Collections.Generic;
    
    public partial class kontrahent
    {
        public int ID { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public Nullable<long> Pesel { get; set; }
        public Nullable<long> NIP { get; set; }
        public string Nazwa_Firmy { get; set; }
        public string Adres { get; set; }
        public string E_mail { get; set; }
        public string Telefon_1 { get; set; }
        public string Telefon_2 { get; set; }
    }
}
