//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_elektryk
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class zlecenieEntities : DbContext
    {
        public zlecenieEntities()
            : base("name=zlecenieEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<kategoria_produktu> kategoria_produktu { get; set; }
        public virtual DbSet<kontrahent> kontrahent { get; set; }
        public virtual DbSet<produkt> produkt { get; set; }
        public virtual DbSet<adres> adres { get; set; }
        public virtual DbSet<produkty_w_wycenie> produkty_w_wycenie { get; set; }
        public virtual DbSet<oferta> oferta { get; set; }
        public virtual DbSet<Dane_Logowania> Dane_Logowania { get; set; }
    }
}
