//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_elektryk
{
    using System;
    using System.Collections.Generic;
    
    public partial class oferta
    {
        public int ID { get; set; }
        public string Nazwa { get; set; }
        public int Id_zleceniodawca { get; set; }
        public System.DateTime Data_Od { get; set; }
        public System.DateTime Data_Do { get; set; }
        public string Opis { get; set; }
        public int Status { get; set; }
    }
}
