//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_elektryk
{
    using System;
    using System.Collections.Generic;
    
    public partial class produkty_w_wycenie
    {
        public int ID_zlecenie { get; set; }
        public int ID_produktu { get; set; }
        public decimal ilość { get; set; }
        public int Marża { get; set; }
    }
}
