//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_elektryk
{
    using System;
    using System.Collections.Generic;
    
    public partial class produkt
    {
        public int ID { get; set; }
        public string Nazwa { get; set; }
        public string Producent { get; set; }
        public string Jm { get; set; }
        public double Ilość { get; set; }
        public decimal Cena_netto { get; set; }
        public double Vat { get; set; }
        public decimal Cena_brutto { get; set; }
        public int Kategoria { get; set; }
        public string Numer_katalogowy { get; set; }
    }
}
